app:
  baselink: http://127.0.0.1:8080/
db: # db properties
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/mailBaseNew?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&createDatabaseIfNotExist=true
  username: root
  password: root
#hibernate properties
hibernate:
  dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  show_sql: true
  format_sql: true
  hbm2ddl:
    auto: update
#    auto: create-drop

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: baseserverhneu@gmail.com
    password: mailserver327
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
#
#scheduled:
#  uuid:
#    signup:
#      livetime: 12
